language: php

php:
  - 7.0

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpcs --standard=PSR2 ./src/

after_script:
  - php vendor/bin/coveralls -v
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
