language: php

php:
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
  - vendor/bin/phpcs --standard=PSR2 ./src/

after_script:
  - php vendor/bin/coveralls -v
